// todo/todo-angular-ui/src/app/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoApiService } from '../service/data/todo-api.service';
import { Router, ActivatedRoute } from '@angular/router';
import { Todo } from '../list-todos/list-todos.component';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {

  id: number 
  todo: Todo

  constructor(
    private todoAPI: TodoApiService,
    private route: ActivatedRoute,
    private router: Router
  ) { }

  ngOnInit() {

    this.id = this.route.snapshot.params['id']
    this.todo = new Todo(this.id, '', false, null)

    if(this.id) {
      console.log(`retrieving id # ${this.id}`)
      this.todoAPI.getTodo(this.id).subscribe(
        data => this.todo = data
      )
    }
  }

  saveTodo() {
    if(this.id) {
      this.todoAPI.updateTodo(this.id, this.todo)
        .subscribe(
          response => {
            // console.log(response)
            this.router.navigate(['todos'])
          }
      )
    } else {
      this.todoAPI.createTodo(this.todo)
        .subscribe(
          response => {
            // console.log(response)
            this.router.navigate(['todos'])
          }
      )
    }
  }


}

<h1>Todo</h1>

<div class="container">
    <div class="alert alert-warning" *ngIf="todoForm.dirty && todoForm.invalid">Enter Valid Values</div>
    <form (ngSubmit)="!todoForm.invalid && saveTodo()" #todoForm="ngForm">
        <fieldset class="form-group">
            <label>Description</label>
            <input type="text" [(ngModel)]="todo.description" class="form-control" name="description" required="required" minlength="5"/>
        </fieldset>
        <fieldset class="form-group">
            <label>Target Date</label>
            <input type="date" 
                [ngModel]="todo.targetDate | date:'yyyy-MM-dd'" 
                (ngModelChange)="todo.targetDate = $event"
                class="form-control" name="targetDate"  required="required" />
        </fieldset>
        <button type="submit" class="btn btn-warning">Save</button>
    </form>
</div>

// todo/todo-react-ui/src/components/todo/TodoComponent.jsx
import React, { Component } from 'react';
import moment from 'moment'
import { Formik, Form, Field, ErrorMessage } from 'formik';
import HelloWorldService from '../../api/todo/TodoService.js';

export class TodoComponent extends Component {
    constructor(props) {
        super(props)

        this.state = {
            id : this.props.match.params.id,
            description : '',
            targetDate : moment.parseZone(new Date()).format('YYYY-MM-DD')
        }
        this.onSubmit = this.onSubmit.bind(this)
        this.validate = this.validate.bind(this)
    }

    componentDidMount() {

        if (this.state.id === -1) return

        HelloWorldService.getTodo(this.state.id)
            .then(
                response => { 
                    console.log(response.data)
                    this.setState({
                        description : response.data.description,
                        targetDate: moment.parseZone(response.data.targetDate).format('YYYY-MM-DD')
                    })
                    console.log("desc: " + this.state.description)
                    console.log("targetdate: " + this.state.targetDate)
                }
            )

        }

    onSubmit(values) {
        console.log(values)

        if (this.state.id === -1) {
            HelloWorldService.addTodo({
                description: values.description,
                targetDate: values.targetDate
            }).then(() => this.props.history.push('/todos'))
        } else {
            HelloWorldService.updateTodo(this.state.id, {
                id: this.state.id,
                description: values.description,
                targetDate: values.targetDate
            }).then(() => this.props.history.push('/todos'))
        }
    }
    
    validate(values) {
        let errors = {}
        if (!values.description) {
            errors.description = 'Enter a Description'
        } else if (values.description.length < 5) {
            errors.description = 'Enter at least 5 characters for Description'
        }

        if(!moment(values.targetDate).isValid) {
            errors.targetDate = 'Enter a valid date'
        }
        return errors
    }

    render() {
        let {description,targetDate}  = this.state
        return (
            <div>
                <h1>Todo</h1>
                <div className="container">
                    <Formik
                        initialValues={{description, targetDate}}
                        onSubmit={this.onSubmit}
                        // validateOnBlur={false}
                        // validateOnChange={false}
                        validate={this.validate}
                        enableReinitialize={true}
                    >
                        {   
                            (props) => (
                                <Form>
                                    <ErrorMessage name="description" component="div" className="alert alert-warning" />
                                    <ErrorMessage name="targetDate" component="div" className="alert alert-warning" />
                                    <fieldset className="form-group row">
                                        <lable>Description</lable>
                                        <Field className="form-control" type="text" name="description"/>
                                    </fieldset>
                                    <fieldset className="form-group row">
                                        <lable>Target Date</lable>
                                        <Field className="form-control" type="date" name="targetDate"/>
                                    </fieldset>
                                    <button className="btn btn-success" type="submit">Save</button>
                                </Form>
                            )

                        }
                    </Formik>
                </div>
            </div>
        )
    }
}
